### ISSUE TITLE
Error found

### ISSUE THREAD

**Issue by gagalina** [gagalina/domashka1#1]
**Pretty cool article**

I would add this in the [alias] section of the ~/.gitconfig file:

`cancel = reset –soft HEAD^`

**Comment by gagalina** [comment]
Ok, I`ll fix this barachlo

**Comment by gagalina** [comment]
Fixed with commit gagalina@d478c90235f070888941e3ed390e73648f6e8467

**Comment by volodymyr-kushnir** [comment]
@gagalina always nice to see _barachlo_ getting fixed. Good work, keep it up.
P. S. Я свій хлам трохи підмарафетив, з [**лайфхаками і тим всім**](https://github.com/volodymyr-kushnir/agenda).
